// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wm9Etz0DIpUFVYZJxX8Ejyuzq7PHfps',
    appId: '1:870077720388:web:f35b8053576167371f9911',
    messagingSenderId: '870077720388',
    projectId: 'flowers-shop-mvp',
    authDomain: 'flowers-shop-mvp.firebaseapp.com',
    storageBucket: 'flowers-shop-mvp.firebasestorage.app',
    measurementId: 'G-9SG27SFPY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApJIe5fn2dZNoh-tB3zdOymAHkVnrIm0',
    appId: '1:870077720388:android:9eb505a4eaaa0ac81f9911',
    messagingSenderId: '870077720388',
    projectId: 'flowers-shop-mvp',
    storageBucket: 'flowers-shop-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgewIQgdWo7hsX0He5Dy7dD1LCS85c7OE',
    appId: '1:870077720388:ios:0a4ca955edb9f6c41f9911',
    messagingSenderId: '870077720388',
    projectId: 'flowers-shop-mvp',
    storageBucket: 'flowers-shop-mvp.firebasestorage.app',
    iosBundleId: 'com.example.flowersShopMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgewIQgdWo7hsX0He5Dy7dD1LCS85c7OE',
    appId: '1:870077720388:ios:0a4ca955edb9f6c41f9911',
    messagingSenderId: '870077720388',
    projectId: 'flowers-shop-mvp',
    storageBucket: 'flowers-shop-mvp.firebasestorage.app',
    iosBundleId: 'com.example.flowersShopMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4wm9Etz0DIpUFVYZJxX8Ejyuzq7PHfps',
    appId: '1:870077720388:web:aac4a004aead8b221f9911',
    messagingSenderId: '870077720388',
    projectId: 'flowers-shop-mvp',
    authDomain: 'flowers-shop-mvp.firebaseapp.com',
    storageBucket: 'flowers-shop-mvp.firebasestorage.app',
    measurementId: 'G-Y9WSLWZWB2',
  );
}
